In [5]:
import numpy as np
first_initial = 'A'  # Change this to your first initial
last_initial = 'B'   # Change this to your last initial

X = ord(first_initial) + ord(last_initial)  # ASCII sum
sales = np.array([X, X+50, X+100, X+150, X+200])

sales

array([131, 181, 231, 281, 331])

In [7]:
tax_rate = ((X % 5) + 5) / 100
taxed_sales = sales * (1 + tax_rate)

tax_rate, taxed_sales

(0.06, array([138.86, 191.86, 244.86, 297.86, 350.86]))

In [12]:
discounted_sales = np.where(sales < X+100, sales * 0.95, sales * 0.90)

discounted_sales

array([124.45, 171.95, 207.9 , 252.9 , 297.9 ])

In [14]:
# Creating a 3×5 matrix
weekly_sales = np.vstack([sales, sales * 1.02, sales * 1.04])

weekly_sales

array([[131.  , 181.  , 231.  , 281.  , 331.  ],
       [133.62, 184.62, 235.62, 286.62, 337.62],
       [136.24, 188.24, 240.24, 292.24, 344.24]])