In [7]:
# Create a 2D Array of three rows and four columns
ucs420_myname = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

# Compute statistical properties
mean_value = np.mean(ucs420_myname)
median_value = np.median(ucs420_myname)
max_value = np.max(ucs420_myname)
min_value = np.min(ucs420_myname)
unique_elements = np.unique(ucs420_myname)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

# Reshape array to 4 rows and 3 columns
reshaped_ucs420_myname = ucs420_myname.reshape(4, 3)
print("Reshaped Array:\n", reshaped_ucs420_myname)

# Resize array to 2 rows and 3 columns
resized_ucs420_myname = ucs420_myname[:2, :3]  # Truncate to fit new shape
print("Resized Array:\n", resized_ucs420_myname)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [50 60 70]]
