In [20]:
import numpy as np
c=np.array([1,2,3,4,5,6,7])
print(c)
c+=2
print(c)

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]


In [22]:
c*=3
print(c)

[ 9 12 15 18 21 24 27]


In [24]:
c//=2
c

array([ 4,  6,  7,  9, 10, 12, 13])