In [31]:
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)
print("Absolute Values:\n", abs_array)

# ii. Percentiles (flattened, per column, per row)
flat_25, flat_50, flat_75 = np.percentile(array.flatten(), [25, 50, 75])
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)

print("Flattened percentiles:", flat_25, flat_50, flat_75)
print("Column-wise percentiles:\n", col_percentiles)
print("Row-wise percentiles:\n", row_percentiles)

# iii. Mean, Median, Standard Deviation
mean_flat, median_flat, std_flat = np.mean(array), np.median(array), np.std(array)
mean_col, median_col, std_col = np.mean(array, axis=0), np.median(array, axis=0), np.std(array, axis=0)
mean_row, median_row, std_row = np.mean(array, axis=1), np.median(array, axis=1), np.std(array, axis=1)

print("Mean, Median, Std (Flattened):", mean_flat, median_flat, std_flat)
print("Mean, Median, Std (Column-wise):\n", mean_col, median_col, std_col)
print("Mean, Median, Std (Row-wise):\n", mean_row, median_row, std_row)

Absolute Values:
 [[1 2 3]
 [4 5 6]]
Flattened percentiles: -3.5 -0.5 2.5
Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean, Median, Std (Flattened): -0.5 -0.5 3.8622100754188224
Mean, Median, Std (Column-wise):
 [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Mean, Median, Std (Row-wise):
 [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]
